### ISSUE TITLE
[Support Request] Data from plan is not syncing to web and dashboard

### ISSUE THREAD

**Issue by AngelaKabari** [onaio/Reveal-Thailand#1]
### What is the nature of this Technical Support Request? Please describe the need/requirement in detail
_(A clear and concise description of what the problem is)_ 

A member of the DVBD field staff is experiencing a problem with a plan id: **5bc3f9c7-5763-5645-a6df-f457c86f03dd** with user: **vbdu_2.1.1-1**.
They filled in the data, then sync completed, but there is no data on the web and dashboard. 

### Describe the solution you'd like
_(A clear and concise description of what you want to happen)_

- Establish what the issue is and remedy it. 
- Get the exported data from the app that the field team have shared and get all data from the plan into the DB.

### Describe alternatives you've considered
None.

### Additional context
_(Add any other context or screenshots about the request here)_

None.

**Comment by ekigamba** [comment]
### Data that is synced on Reveal Thailand

- Events
- Client
- Tasks - Requires a custom SQL to generate a JSON for each record and then merge these JSONs as a list
- Structures (`structures` table) JSON column contains everything required for sync


cc @AngelaKabari

This means that I need to upload the structures from the users data dump

**Comment by AngelaKabari** [comment]
Thanks for the update @ekigamba. Let me know when this is complete?

**Comment by ekigamba** [comment]
@AngelaKabari I have uploaded 99 structures to Reveal for this user. This should have reflected by tomorrow morning

**Comment by AngelaKabari** [comment]
Hello @ekigamba I've just checked the Reveal Web Dashboard and the structures are still not displaying in both focus investigation plan pages (views and map). Kindly take a look at it again?

**Comment by ekigamba** [comment]
- On the map page https://mhealth.ddc.moph.go.th/focus-investigation/map/7015b227-1a4a-56b9-b5c4-9c60e4b151db, I can see that the page is loading the 99 structures from the network requests but they are still not displaying once you click on the **household registration**
- On the plan view page https://mhealth.ddc.moph.go.th/focus-investigation/view/5bc3f9c7-5763-5645-a6df-f457c86f03dd,  nothing is loading and we get the same error. The network request made is using the plan id as the jurisdiction id when fetcthing the structures from Superset/Canopy

**Comment by AngelaKabari** [comment]
Thanks @ekigamba let me loop in the OpenSRP Web Team to help troubleshoot this.

**Comment by p-netm** [comment]
1. The single Active FI map view on page: https://mhealth.ddc.moph.go.th/focus-investigation/map/7015b227-1a4a-56b9-b5c4-9c60e4b151db does not load/display points on the map. This data is computed from the tasks, slice `8`.

The request to fetch the data fails with a 403 error.
```
https://supersetmhealth.ddc.moph.go.th/superset/slice_json/8?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SQL%22,%22sqlExpression%22:%22(plan_id%20=%20%275bc3f9c7-5763-5645-a6df-f457c86f03dd%27)%20OR%20\n%20%20%20%20%20%20%20%20%20%20%20%20(jurisdiction_id%20=%20%2794c94f23-568a-4467-8959-5d02b8f9f49f%27%20AND%20goal_id%20=%20%27Case_Confirmation%27)%22}],%22row_limit%22:250}
```

Running it on the browser yields this view:
![Screenshot from 2023-01-17 09-26-52](https://user-images.githubusercontent.com/28119869/212844218-d975086d-c79a-4299-b5f8-1ede2f53f847.png)

@AngelaKabari I understand we are not in control of the firewall, I would suggest reaching to the client's technical team to confirm why they firewall fails this request or if  the issue lies elsewhere else. cc @bennsimon .

2. The plan view page, or rather the FI jurisdiction view, displays a list of FI plans for a given operational area. I am not sure what steps were taken to arrive at this url:  https://mhealth.ddc.moph.go.th/focus-investigation/view/5bc3f9c7-5763-5645-a6df-f457c86f03dd, but I think its malformed, the id at the end of the url should be that of a jurisdiction and not a plan. I think the correct url, which is what the web app would direct you to is https://mhealth.ddc.moph.go.th/focus-investigation/view/94c94f23-568a-4467-8959-5d02b8f9f49f.

**Comment by AngelaKabari** [comment]
@p-netm I shall check with DVBD what's going on with the firewall as it is also created #15 where routine action plans are not being generated.

**Comment by AngelaKabari** [comment]
Hello @p-netm the Reveal Thailand system is back online so let us pick this us again next week.

**Comment by p-netm** [comment]
@AngelaKabari 
- I can confirm the error on the tasks slice is no longer showing up, the web app is actually receiving tasks data from superset.
- Each task among a few other fields contains a geojson field. the web app uses the geometry property in the geojson to draw the points on the map
- The problem now seems to be that  all the tasks for this plan `5bc3f9c7-5763-5645-a6df-f457c86f03dd` do not have a geometry in their geojson.

cc @HusnaHariz

**Comment by AngelaKabari** [comment]
Thanks for getting to the root of this. @p-netm I think the missing geometry in the geojsons for the tasks might be stemming from the manual addition of those tasks to the database from the user's data dump. Let me consult @Rkareko and @ekigamba on this before we loop @HusnaHariz back in.

**Comment by ekigamba** [comment]
@AngelaKabari I can confirm that I uploaded the structures containing the geojson. The tasks reference these structures. 

Is there someone who can explain why this was happening?
> On the map page [mhealth.ddc.moph.go.th/focus-investigation/map/7015b227-1a4a-56b9-b5c4-9c60e4b151db](https://mhealth.ddc.moph.go.th/focus-investigation/map/7015b227-1a4a-56b9-b5c4-9c60e4b151db), I can see that the page is loading the 99 structures from the network requests but they are still not displaying once you click on the household registration

cc @Rkareko

**Comment by Wambere** [comment]
@ekigamba is it possible to share some of the manually uploaded tasks ans structure ids, so we can try track them in the warehouse?

**Comment by p-netm** [comment]
Had a chance to look at this yesterday with a lot of help from @HusnaHariz @lincmba  and @ekigamba . Let me know if I missed anything or need to add more contextual info.

so what we knew:
- The tasks from superset do not have geometries.
- The tasks were manually uploaded to the OpenSRP db .

 
 What we checked:
- Identified the the data source to the tasks slice on superset, which is `task_structures_geojson_slice`
 - Identified that the slice datasource  [task_structures_geojson_slice](https://github.com/opensrp/opensrp-reveal-datawarehouse/blob/master/3-reveal/superset/task_structures_geojson_slice.sql) uses the `task_structures_materialized_view` materialized view.
 - The [task_structures_materialized_view](https://github.com/opensrp/opensrp-reveal-datawarehouse/blob/dcc24093b70855d1def353a509d53063ce5d3311/3-reveal/migrations/4-FI/1-Thailand-2019/deploy/task_structures_materialized_view.psql) mat view computes a task geometry from a join  of the transactional tables `tasks` and `locations`  based on `task.task_for` and `locations.locationId`
 - Inspected the tasks transactional table
 	- Noticed tasks for this plan had the `task_for` field set to NULL.

- Checked NIFI to see what field in the `raw_task` table is mapped to the `tasks` transactional table for the `task_for` field.
- Noticed the raw_tasks were missing the `geojson ->> for` field.
- Confirmed the tasks in the opensrp db were also missing the `geojson ->> for` field.
- Regenerated the tasks with the correct values for `geojson ->> for` and re-uploaded them to the opensrp db.
- Re-ran the ETL to update the `raw_tasks` in the canopy warehouse, and also updated tasks data being served by the `task_structures_materialized_view`

![image](https://user-images.githubusercontent.com/28119869/216273133-5534cc44-73fe-4fe5-91f6-ea6776d12630.png)

**Comment by AngelaKabari** [comment]
Thanks @p-netm both for your hard work and for this very comprehensive explanation. I appreciate the level of detail. Thank you too @ekigamba, @lincmba, and @HusnaHariz for your valuable input into troubleshooting and resolving this.

I have checked and the structures are displaying as they should on Reveal Web.

@pongthepm kindly ask DVBD to confirm that this has been satisfactorily resolved so that we can close it out?
