### ISSUE TITLE
[Technical Support Request] Reveal web deployment problem

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#20]
Hi,
I am not sure if we have deployed the reveal web successfully or not, but we got no error in the deployment status. However, we noticed that when compared between your preview and my bioppreview, there is no directory react and the link react on my file system. Please see the attached images.

Could you please advise?
Thank you,
Pongthep

![compare-preview-Vs-bioppreview](https://user-images.githubusercontent.com/119026101/216243186-c284b4c7-d579-42c9-8b4d-3027d60ce3ca.jpg)
![reveal-web-deploy-success](https://user-images.githubusercontent.com/119026101/216243196-387b73d3-5902-4e6c-9e77-689e6273506e.jpg)
![web-error](https://user-images.githubusercontent.com/119026101/216243204-884b471b-1f72-45d4-9e64-453089d6cd01.JPG)

**Comment by AngelaKabari** [comment]
I confirm receipt of this issue @pongthepm and will ask @p-netm to take a look at it.

**Comment by p-netm** [comment]
@pongthepm what's the ansible-playbook command that was used to deploy this. I would like to confirm that the `react` tag was not skipped.

**Comment by pongthepm** [comment]
Mix will send you the command.

**Comment by gumixjung** [comment]
command: ansible-playbook -i ../Reveal-Thailand/ansible/inventories/bioppreview/opensrp-stack/ reveal-web.yml --vault-password=~/.vaultpass  -e ansible_user=ubuntu -e ansible_ssh_user=ubuntu

vars.yml:
[vars.yml.zip](https://github.com/onaio/Reveal-Thailand/files/10567985/vars.yml.zip)


ref: https://github.com/onaio/Reveal-Thailand/blob/main/docs/preview-infrastructure.md

**Comment by p-netm** [comment]
@gumixjung thoughtful of you to share the extra details. The details you share looks okay. @AngelaKabari I think we can have a pairing session to look into this. We can do so in the next reveal-web session or create one before then, depending on the urgency of this

**Comment by gumixjung** [comment]
I think in playbooks/roles/react  is empty folder 
I download and run 
err:
TASK [react : Install Javascript requirements locally] **********************************************************************************************************************************************************************************************************************
fatal: [application-server]: FAILED! => {"changed": false, "msg": "Failed to find required executable yarn in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}

**Comment by AngelaKabari** [comment]
@pongthepm and @gumixjung I believe this can wait the 2 working days until the next Reveal Web session on Tuesday 7th February, no? But please let me know if you would prefer to have the pairing session earlier?

**Comment by pongthepm** [comment]
OK, Angela. We can wait. 
In the meantime, @p-netm if you want us to check another point or anything else. We can do for you. 
Thank you for your support,
Pongthep

**Comment by p-netm** [comment]
>  I think in playbooks/roles/react is empty folder

you can check if there are files in the `playbooks/roles/react` and confirm if its empty. I however do not think its empty since this task fails, which means it must exist.

> ******************************************************************* fatal: [application-server]: FAILED! => {"changed": false, "msg": "Failed to find required executable yarn in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}

This is very helpful, seems like you do not have yarn installed locally
You can do so in 2 ways.
- Installing it globally i.e. `npm install -g yarn`
- [Recommended: Install node >= v16.10 and enable corepack](https://yarnpkg.com/getting-started/install)


You probably know this but to backfill
The `reveal_react_remote_js_build` inventory variable is set to false, this means the react application build will happen locally on the machine that is executing the ansible-playbook command.  As such you need to have node and yarn installed locally, I will add to the reveal-web google doc.

**Comment by pongthepm** [comment]
Hi @p-netm 
Let Mix take a look and do as per your recommendation. 
Thank you for your support,
Pongthep

**Comment by p-netm** [comment]
@pongthepm Any errors in the nginx error log file?

**Comment by pongthepm** [comment]
Hi @p-netm and @AngelaKabari 
Mix has deployed the reveal web successfully. 
Thank you for your support,
Pongthep
![fe-login-OK@07Feb2023](https://user-images.githubusercontent.com/119026101/217132827-f7e07d8f-9253-46a5-ab5d-ee84b7d0e5b0.JPG)

**Comment by AngelaKabari** [comment]
This is excellent news! Kudos on succeeding with this. 

I'm now closing this issue out. Please feel free to re-open it if anything else comes up down the line.
