### ISSUE TITLE
[Support Request]: The site user created a routine activity plan, but there was no user assigned automatically

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#23]
Problem: The site user created a routine activity plan, but there was no user assigned automatically (image #1). This caused the plan were not showing on the tablet. The user could not bring the tablet for data entering. The BVBD staff checked and found that this problem may be happened since Jan 24, 2023 till it was expired and no user could be assigned.

So, to fixed this problem, the BVBD staff assigned the user for the particular plan in case by case. The staff manually type in the url and assign the user (image #2)

Sometimes, this problem happened in both routine and RACD plan activities.

Thank you for your support,
Pongthep
![1676539533557](https://user-images.githubusercontent.com/119026101/220005325-852b7632-68f8-4afc-9cf3-fffc839ea711.jpg)
![1676539538205](https://user-images.githubusercontent.com/119026101/220005331-cfcc5747-4d93-47f9-a9f7-7487674ed990.jpg)

**Comment by AngelaKabari** [comment]
Hello @pongthepm I confirm that we have received this issue. Let us look into it then get back to you with the next steps.

**Comment by HusnaHariz** [comment]
The [Process Group (PG)](https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=f093346e-941b-1fdf-f0a3-34cb8d125cc9&componentIds=) responsible for user assignment was not running. The PG had some restructuring work done to remove processors that were no longer relevant to the flow to ensure a simplified/cleaner PG was handed over to the client for the preview training. 

This has been restarted

**Comment by AngelaKabari** [comment]
Thanks for the feedback and speedy action on this @HusnaHariz. 

@pongthepm could you please check with DVBD to confirm whether this has been satisfactorily resolved?

**Comment by pongthepm** [comment]
Dear @AngelaKabari,
Namkang told me that the problem is now fixed. The user is assigned to the plan successfully.
Thank you for your support,
Pongthep

**Comment by AngelaKabari** [comment]
Thanks, I'm closing this out. Please re-open it if you need any further support?
