### ISSUE TITLE
Check if the domains are still under using in the system

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#25]
Hi,
The IT department of DDC, MoPH who provides the domain names of the malaria mHealth system wants to know which following domains are under using and which are not. By myself I know which ones are using, but I am not sure a couple domains, could you please confirm?

Thank you,
Pongthep 

1. Domain: malariamhealth.ddc.moph.go.th	
2. Domain: keycloakmhealth.ddc.moph.go.th
3. Domain: servermhealth.ddc.moph.go.th
4. Domain: supersetmhealth.ddc.moph.go.th
5. Domain: nifimhealth.ddc.moph.go.th
6. Domain: mhealth.malaria.ddc.moph.go.th
7. Domain: malariaapp.ddc.moph.go.th

**Comment by AngelaKabari** [comment]
@pongthepm please find the response below from our SRE team: 

              Hey @AngelaKabari, the domains that are not in use are:
```
1. malariaapp.ddc.moph.go.th
2. malariamhealth.ddc.moph.go.th
3. mhealth.malaria.ddc.moph.go.th
```

_Originally posted by @bennsimon in https://github.com/onaio/infrastructure/issues/6311#issuecomment-1443358940_

**Comment by AngelaKabari** [comment]
@pongthepm let me know if you need any further assistance on this? If not, please close the issue?

**Comment by pongthepm** [comment]
Thank you for your support.
Pongthep
