### ISSUE TITLE
[Technical Support Request] No household locations on the map after successful data synchronization

### ISSUE THREAD

**Issue by pongthepm** [onaio/Reveal-Thailand#30]
The site staff successfully synchronized the data on the tablet, but when he checked the data on the Reveal web, he found that there were no any household locations on the map. Please see the attached images.

user: 5.2.1-1  (เพชรบุรี)
แผนงานตอบโต้ (RACD)
A1 - ลิ้นช้าง (7603020301) - ธนัชญา ชาดี - 2023-03-14 - Source
id: af29e632-3c3a-4930-82b0-4e9e2e2646c7

แผนงานปกติ (Routine)
A1 บางกลอย (7608060101) 2023-03-08 เจาะเลือดก่อนฤดูกาล (PACD)
id: 83dae66c-946d-57c1-84f5-44ff38413ac2

A1 โป่งลึก (7608060201) 2023-03-08 เจาะเลือดก่อนฤดูกาล (PACD)
id: f0ee9655-ee60-501e-97ce-ae401781ce5c
![1680161715864](https://user-images.githubusercontent.com/119026101/228890548-14e8db4a-c34c-4029-802b-a0b0a11c589a.jpg)
![1680161538851](https://user-images.githubusercontent.com/119026101/228890558-87e285bf-2e40-49fa-9a9c-1b8a45bca9e8.jpg)

**Comment by truongnt** [comment]
@pongthepm Can you ask technical guys to look at this, sounds like similar issue: #1 #12.

Potentially missing data somewhere, due you are working on database design, it is good to know which are missing, !

**Comment by AngelaKabari** [comment]
Closing this issue as it has been overtaken by events and the project has come to an end.
