### ISSUE TITLE
[Technical Support Request] Check Nifi 

### ISSUE THREAD

**Issue by truongnt** [onaio/Reveal-Thailand#34]
## What is the nature of this Technical Support Request? Please describe the need/requirement in detail.
Check the endpoint to make sure it is ruining with purpose? it is holding gigas.

![image](https://github.com/onaio/Reveal-Thailand/assets/2433196/e7c75dbd-5b29-4180-8f88-7b3b45520565)

## Additional context
Add any other context or screenshots about the request here.

**Comment by AngelaKabari** [comment]
Hello @truongnt,

I confirm receipt of this ticket. We shall look into it shortly.

**Comment by HusnaHariz** [comment]
@AngelaKabari @truongnt The pipeline is not required and has been deleted with the flowfiles. It was put in place to help with troubleshooting previous issues.

**Comment by truongnt** [comment]
Thanks
